### ISSUE TITLE
markerview 由上边的图表跟随高亮线滑到下面的图表怎么实现呢？

### ISSUE THREAD

**Issue by Anayuta** [gzw19931217/android-kline#3]

**Comment by gzw19931217** [comment]
这个类实现这个功能，可以参考下：
https://github.com/gzw19931217/android-kline/blob/master/klinelib/src/main/java/com/guoziwei/klinelib/chart/InfoViewListener.java

**Comment by Anayuta** [comment]
@gzw19931217 好的，我看看。谢谢了。

**Comment by Anayuta** [comment]
大概看了一下，好像回答的不是同一个问题。就是和同花顺边上的markerview一样，跟随横向高亮线跨表移动
